# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bytes-message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bytes-message.proto',
  package='proto',
  serialized_pb=_b('\n\x13\x62ytes-message.proto\x12\x05proto\",\n\x0c\x42ytesMessage\x12\x0e\n\x06header\x18\x01 \x03(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x11\n\x05protoB\x08ProtoBuf')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BYTESMESSAGE = _descriptor.Descriptor(
  name='BytesMessage',
  full_name='proto.BytesMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.BytesMessage.header', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.BytesMessage.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['BytesMessage'] = _BYTESMESSAGE

BytesMessage = _reflection.GeneratedProtocolMessageType('BytesMessage', (_message.Message,), dict(
  DESCRIPTOR = _BYTESMESSAGE,
  __module__ = 'bytes_message_pb2'
  # @@protoc_insertion_point(class_scope:proto.BytesMessage)
  ))
_sym_db.RegisterMessage(BytesMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\005protoB\010ProtoBuf'))
# @@protoc_insertion_point(module_scope)
